User Login System/LoginSystemProject/LoginSystemApp/urls.py
from django.urls import path
from LoginSystemApp import views

app_name = 'LoginSystemApp'

urlpatterns = [
    path('', views.index,name='index' ),
    path('register/', views.register,name='register' ),
    path('login/', views.user_login,name='login' ),
    
]

User Login System/LoginSystemProject/LoginSystemProject/urls.py
from django.contrib import admin
from django.urls import path,include
from LoginSystemApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('LoginSystemApp.urls')),
    path('logout/', views.user_logout,name='logout' ),

]

User Login System/LoginSystemProject/LoginSystemApp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):

        return self.user.username
    

User Login System/LoginSystemProject/LoginSystemApp/forms.py
from django.contrib.auth.models import User
from LoginSystemApp.models import UserInfo
from django import forms
from django.forms import TextInput,ModelForm,EmailInput,PasswordInput

class UserForm(forms.ModelForm):
    
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('first_name','last_name','username','email','password')
        widgets ={
            'first_name':TextInput(attrs={'class':'form-control','placeholder':'First Name'}),
            'last_name':TextInput(attrs={'class':'form-control','placeholder':'Last Name'}),
            'username':TextInput(attrs={'class':'form-control','placeholder':'Username'}),
            'email':EmailInput(attrs={'class':'form-control','placeholder':'Email'}),
            'password':PasswordInput(attrs={'class':'form-control','placeholder':'Password'}),
        }


class ProfileForm(forms.ModelForm):
    
    class Meta:
        model = UserInfo
        fields = ('profile_pic',)
        

User Login System/LoginSystemProject/LoginSystemApp/views.py
from django.shortcuts import render
from LoginSystemApp.forms import UserForm,ProfileForm
from django.contrib.auth.models import User

from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse

# Create your views here.

def index(request):

    return render(request,'LoginSystemApp/index.html')

def register(request):

    registered = False
    user_form = UserForm()
    profile_form = ProfileForm()

    if request.method  == 'POST':

        user_form = UserForm(request.POST)
        profile_form = ProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()

            user.set_password(user.password)

            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
            
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:

            print(user_form.errors,profile_form.errors)
    else:
       
        user_form = UserForm()
        profile_form = ProfileForm()
       
    return render(request,'LoginSystemApp/register-form.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})



def user_login(request):

    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:

            if user.is_active:

                login(request,user)

                return HttpResponseRedirect(reverse('LoginSystemApp:index'))
        
            else:

                return HttpResponse('Account not exists')
        else:

            return HttpResponse('User not found')
    
    return render(request,'LoginSystemApp/login-form.html',{})
 
@login_required
def user_logout(request):

    logout(request)

    return HttpResponseRedirect(reverse('LoginSystemApp:index'))

User Login System/LoginSystemProject/templates/LoginSystemApp/base.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"><body>
    
    {% block body_block  %}
        


    {% endblock %}
    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>   
  
</body>
</html>

User Login System/LoginSystemProject/templates/LoginSystemApp/footer.html
{% block body_block %}

<div class="footer bg-dark fixed-bottom">
    <div class="container">
                <p class="text-center text-white small mt-3">
                    &copy; copyright by Ankur Kaul | All Rights Reserved | 2023
                </p>
    </div>
</div>

{% endblock %}

User Login System/LoginSystemProject/templates/LoginSystemApp/header.html
{% block body_block  %}
<nav class="navbar navbar-expand-lg bg-body-tertiary navbar-dark bg-dark">
    <div class="container">

              <a class="navbar-brand" href="{% url 'LoginSystemApp:index' %}">Logo</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'LoginSystemApp:index' %}">Home</a>
                  </li>
                </ul>
                <ul class="navbar-nav">
                  {% if user.is_authenticated %}
                  <li class="nav-item text-white mt-2">
                    {{user.username}}
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                  </li>
                  {% else %}
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'LoginSystemApp:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'LoginSystemApp:register' %}">Register</a>
                    </li>                    
                  {% endif %}
                    
                  </ul>
              </div>

    </div>
</nav>
{% endblock  %}

User Login System/LoginSystemProject/templates/LoginSystemApp/index.html
{% extends 'LoginSystemApp/base.html' %}

{% block body_block %}

    {% include 'LoginSystemApp/header.html' %}


    {% include 'LoginSystemApp/footer.html' %}

{% endblock %}

User Login System/LoginSystemProject/templates/LoginSystemApp/login-form.html
{% extends 'LoginSystemApp/base.html' %}
{% block body_block %}

        <div class="container">

          <div class="form-container border border-primary" style="width: 650px; margin: 200px auto; padding:50px 30px; border-radius:5px;">
      
              <h2 class="text-center text-primary mb-5">Sign In</h2>
      
              <form action="{% url 'LoginSystemApp:login' %}" method="post">
                
                <div class="form-group">
                  <input type="text" class="form-control" name='username' id="username" aria-describedby="emailHelp" placeholder="Enter username">
                </div>
                <div class="form-group">
                  <input type="password" class="form-control" name='password' id="password" placeholder="Password">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
                {% csrf_token %}
                
                <p class="mt-4">Don't have an account <a href="{% url 'LoginSystemApp:register' %}">Sign Up</a></p>

          </div>
      </div>

</div>

{% endblock %}

User Login System/LoginSystemProject/templates/LoginSystemApp/register-form.html
{% extends 'LoginSystemApp/base.html' %}
{% load crispy_forms_tags %}

{% block body_block %}

<div class="container">

    <div class="form-container border border-primary" style="width: 650px; margin: 200px auto; padding:50px 30px; border-radius:5px;">

        <h2 class="text-center text-primary mb-5">Sign Up</h2>

        <form action="" method="POST" class='' enctype="multipart/form-data">
          
            {% for user in user_form %}
              <div class="form-group">
                {{user}}
              </div>   
              {% csrf_token %}           
            {% endfor %}
    
            {% for profile in profile_form %}
              <div class="form-group">
                {{profile}}
              </div>
              {% csrf_token %}
            {% endfor %}             
    
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>     
        <p class="mt-4">Already have an account <a href="{% url 'LoginSystemApp:login' %}">Sign In</a></p>  
    </div>
</div>

{% endblock %}